package(default_visibility = ["//visibility:public"])

cc_library(
    name = "turing",
    deps = [
        "//nexus/turing/common",
        "//nexus/turing/core",
        "//nexus/turing/proto",
    ]
)